import type { University } from './types'

export const localUniversities: University[] = [
  {
    slug: 'sage-university-indore',
    name: 'Sage University Indore',
    shortName: 'SUI',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'A',
    established: 2017,
    about: 'Sage University Indore is one of MP\'s fastest-growing private universities, offering a wide spectrum of UG, PG and doctoral programs across management, engineering, law, sciences, pharmacy, and design. Known for industry-aligned curricula and vibrant campus life.',
    highlights: ['Strong placement record with 500+ recruiters', 'Modern campus with hostel facilities', 'Multiple specialisations in MBA & BBA', 'Approved by UGC, AICTE, BCI, PCI'],
    facilities: ['Hostel', 'Library', 'Sports Complex', 'Labs', 'Cafeteria', 'Wi-Fi Campus'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: ['HR', 'Marketing & Management', 'Finance', 'Event Management', 'Aviation'], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'Mechanical', 'Civil', 'AI/ML'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'UG', name: 'BA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'UG', name: 'BSc Nursing', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: ['Marketing', 'HRM', 'Finance', 'Event Management', 'Applied Management', 'Logistics & SCM', 'Retail', 'AI', 'Real Estate', 'Hospital Administration'], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc (CS/IT) with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'PG', name: 'M.Pharm', specializations: [], eligibility: 'B.Pharm with 55% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB/BA LLB with 55% marks' },
      { level: 'PG', name: 'PhD', specializations: [], eligibility: 'PG with 55% marks + entrance' },
    ],
    website: 'https://sageuniversity.in',
    logo: '',
  },
  {
    slug: 'svvv-indore',
    name: 'Shri Vaishnav Vidyapeeth Vishwavidyalaya',
    shortName: 'SVVV',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'A',
    established: 2015,
    about: 'SVVV is a UGC-recognized private university in Indore dedicated to value-based education. It offers programmes in management, engineering, commerce, law, and sciences with a focus on holistic development and industry readiness.',
    highlights: ['UGC recognized university', 'IBM collaboration for MBA', 'Healthcare & Hospital Mgmt specialisation', 'Active placement cell'],
    facilities: ['Hostel', 'Library', 'Labs', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'UG', name: 'BA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: ['Executive MBA', 'General MBA', 'IBM Collaboration', 'Healthcare & Hospital Management'], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'PG', name: 'M.Com', specializations: [], eligibility: 'B.Com with 50% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB/BA LLB with 55% marks' },
    ],
    website: 'https://svvv.edu.in',
    logo: '',
  },
  {
    slug: 'renaissance-university-indore',
    name: 'Renaissance University',
    shortName: 'RUI',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'A',
    established: 2019,
    about: 'Renaissance University is a forward-thinking private university offering innovative programs including a Harvard-certified MBA+PGB in Business Analytics. It blends global curriculum with local relevance, particularly strong in management, law, and technology programmes.',
    highlights: ['MBA+PGB with Harvard Certificate in Business Analytics', 'PGDBM 360 — industry-focused diploma', 'Strong law school with LLM programme', 'BBA with unique specialisations in Investment Banking & Digital Branding'],
    facilities: ['Hostel', 'Library', 'Digital Classrooms', 'Moot Court', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: ['General/Hons', 'Digital Branding', 'Investment Banking', 'Human Behavior & Psychology'], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'UG', name: 'BA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Ed', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MBA', specializations: ['Hospital Administration'], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MBA + PGB Business Analytics', specializations: ['Harvard Certificate'], eligibility: 'Graduation with 50% marks' },
      { level: 'Diploma', name: 'PGDBM 360', specializations: ['Marketing', 'Finance', 'HR', 'Operations', 'Supply Chain'], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB with 55% marks' },
      { level: 'Diploma', name: 'D.Pharm', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
    ],
    website: 'https://rui.edu.in',
    logo: '',
  },
  {
    slug: 'lnct-university-indore',
    name: 'LNCT University',
    shortName: 'LNCT',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'A',
    established: 2017,
    about: 'LNCT University is a well-established private university in Indore offering a comprehensive range of technical and professional programmes. With multiple campuses across MP, LNCT is among the largest university groups in central India.',
    highlights: ['One of MP\'s largest university groups', 'Strong engineering & management faculties', 'AICTE & UGC approved', 'Placement-focused curriculum'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'UG', name: 'B.Ed', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'PG', name: 'M.Pharm', specializations: [], eligibility: 'B.Pharm with 55% marks' },
      { level: 'Diploma', name: 'Diploma Engineering', specializations: [], eligibility: '10th pass with 35% marks' },
    ],
    website: 'https://lnctuniversity.com',
    logo: '',
  },
  {
    slug: 'medicaps-university-indore',
    name: 'Medicaps University',
    shortName: 'Medicaps',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'A',
    established: 2016,
    about: 'Medicaps University is a NAAC-accredited private university offering quality education across engineering, management, law, commerce, sciences, and pharmacy. It is known for its strong placement record and state-of-the-art infrastructure.',
    highlights: ['NAAC A Grade accreditation', 'Strong placement cell', 'Integrated law programmes', 'Modern campus infrastructure'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports', 'Cafeteria', 'Wi-Fi'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'UG', name: 'BA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB with 55% marks' },
    ],
    website: 'https://medicaps.ac.in',
    logo: '',
  },
  {
    slug: 'ips-academy-indore',
    name: 'IPS Academy',
    shortName: 'IPS',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Deemed University',
    naac: 'A',
    established: 1994,
    about: 'IPS Academy is a UGC-recognized Deemed University with over 25 years of excellence in education. It offers diverse programmes across engineering, management, law, architecture, pharmacy, and sciences from its expansive Indore campus.',
    highlights: ['Deemed University status since 2012', 'Architecture programme (B.Arch)', 'Pharmacy & nursing faculties', 'Strong alumni network'],
    facilities: ['Hostel', 'Labs', 'Library', 'Architecture Studio', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'B.Arch', specializations: [], eligibility: '10+2 (PCM) with 50% + NATA' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'PG', name: 'M.Pharm', specializations: [], eligibility: 'B.Pharm with 55% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB with 55% marks' },
    ],
    website: 'https://ipsacademy.org',
    logo: '',
  },
  {
    slug: 'prestige-university-indore',
    name: 'Prestige University',
    shortName: 'Prestige',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'B+',
    established: 2018,
    about: 'Prestige University offers a wide range of undergraduate, postgraduate and professional courses in management, commerce, law, sciences, engineering and technology. It is known for its industry-connected faculty and career-focused programmes.',
    highlights: ['Wide programme portfolio', 'Integrated law programmes', 'Industry-connected faculty', 'Active placement cell'],
    facilities: ['Hostel', 'Library', 'Labs', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'UG', name: 'BA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA LLB', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB with 55% marks' },
    ],
    website: 'https://prestigeuniversity.ac.in',
    logo: '',
  },
  {
    slug: 'aku-indore',
    name: 'Dr. APJ Abdul Kalam University',
    shortName: 'AKU',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'B+',
    established: 2019,
    about: 'Dr. APJ Abdul Kalam University (AKU) is named after India\'s beloved President and Scientist. It provides quality education in engineering, management, law, pharmacy and sciences, inspiring students to reach for excellence.',
    highlights: ['Named after Dr. APJ Abdul Kalam', 'Diverse programme offerings', 'Affordable fee structure', 'Supportive learning environment'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB with 55% marks' },
    ],
    website: 'https://akuindore.ac.in',
    logo: '',
  },
  {
    slug: 'oriental-university-indore',
    name: 'Oriental University',
    shortName: 'Oriental',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'B+',
    established: 2011,
    about: 'Oriental University is one of Indore\'s established private universities offering programmes in management, engineering, pharmacy, education, commerce and sciences. It focuses on producing industry-ready graduates through practical training.',
    highlights: ['Established private university', 'Pharmacy & B.Ed programmes', 'Industry-oriented training', 'Multiple hostels on campus'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'UG', name: 'B.Ed', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'Diploma', name: 'D.Pharm', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
    ],
    website: 'https://orientaluniversity.in',
    logo: '',
  },
  {
    slug: 'sri-aurobindo-university-indore',
    name: 'Sri Aurobindo University',
    shortName: 'SAU',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'A',
    established: 2013,
    about: 'Sri Aurobindo University draws inspiration from the philosophy of Sri Aurobindo and The Mother, offering programmes that blend academic excellence with holistic development. Strong in pharmacy, sciences, education, and yoga & naturopathy.',
    highlights: ['Unique Yoga & Naturopathy programme', 'Strong pharmacy faculty', 'Philosophy-inspired holistic education', 'B.Ed & teacher training'],
    facilities: ['Hostel', 'Library', 'Labs', 'Yoga Centre', 'Sports'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Ed', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'UG', name: 'BSc', specializations: ['Biotechnology', 'Microbiology'], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'BSc Yoga & Naturopathy', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'PG', name: 'M.Pharm', specializations: [], eligibility: 'B.Pharm with 55% marks' },
    ],
    website: 'https://sau.ac.in',
    logo: '',
  },
  {
    slug: 'malwanchal-university-indore',
    name: 'Malwanchal University',
    shortName: 'Malwanchal',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Medical University',
    naac: 'B+',
    established: 2016,
    about: 'Malwanchal University is a prominent medical and multi-disciplinary university in Indore offering MBBS, BDS, nursing, pharmacy and allied health sciences along with management and engineering programmes. It is one of few private medical universities in MP.',
    highlights: ['MBBS & BDS programmes', 'NMC approved medical college', 'Nursing & GNM/ANM programmes', 'Full-fledged hospital on campus'],
    facilities: ['Hospital', 'Hostel', 'Labs', 'Library', 'Sports'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BDS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BSc Nursing', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MD / MS', specializations: [], eligibility: 'MBBS + NEET-PG' },
      { level: 'PG', name: 'MDS', specializations: [], eligibility: 'BDS + NEET-PG' },
      { level: 'PG', name: 'M.Pharm', specializations: [], eligibility: 'B.Pharm with 55% marks' },
      { level: 'Diploma', name: 'GNM', specializations: [], eligibility: '10+2 (PCB) with 40% marks' },
      { level: 'Diploma', name: 'ANM', specializations: [], eligibility: '10+2 with 40% marks' },
    ],
    website: 'https://malwanchaluniversity.com',
    logo: '',
  },
  {
    slug: 'index-medical-college-indore',
    name: 'Index Medical College (Index University)',
    shortName: 'Index',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Medical University',
    naac: 'B+',
    established: 2001,
    about: 'Index Medical College is a well-established medical institution in Indore, offering MBBS, BDS, nursing, and pharmacy programmes. Associated with a 700-bed teaching hospital, it provides extensive clinical training.',
    highlights: ['700-bed teaching hospital', 'NMC recognised MBBS programme', 'Strong clinical training', 'BDS & specialty dental programmes'],
    facilities: ['Hospital', 'Hostel', 'Labs', 'Library', 'Simulation Centre'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BDS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BSc Nursing', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'PG', name: 'MD / MS', specializations: [], eligibility: 'MBBS + NEET-PG' },
      { level: 'PG', name: 'MDS', specializations: [], eligibility: 'BDS + NEET-PG' },
      { level: 'PG', name: 'M.Pharm', specializations: [], eligibility: 'B.Pharm with 55% marks' },
      { level: 'Diploma', name: 'GNM', specializations: [], eligibility: '10+2 (PCB) with 40% marks' },
      { level: 'Diploma', name: 'ANM', specializations: [], eligibility: '10+2 with 40% marks' },
    ],
    website: 'https://indexmedical.ac.in',
    logo: '',
  },
  {
    slug: 'jaipuria-indore',
    name: 'Jaipuria Institute of Management',
    shortName: 'Jaipuria',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous B-School',
    naac: 'A',
    established: 2013,
    about: 'Jaipuria Institute of Management, Indore is a premier management institution with NAAC A grade accreditation. Part of the prestigious Jaipuria Group with campuses across India, it is known for its PGDM and MBA programmes with strong industry connections.',
    highlights: ['NAAC A Grade accredited', 'Part of pan-India Jaipuria Group', 'Strong industry partnerships', 'Excellent placement record'],
    facilities: ['Hostel', 'Library', 'Digital Classrooms', 'Auditorium', 'Sports'],
    courses: [
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'PGDM', specializations: ['Marketing', 'Finance', 'HR', 'Operations', 'International Business'], eligibility: 'Graduation with 50% marks + entrance' },
    ],
    website: 'https://indore.jaipuria.ac.in',
    logo: '',
  },
  {
    slug: 'amity-business-school-indore',
    name: 'Amity Business School Indore',
    shortName: 'Amity Indore',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Deemed University',
    naac: 'A+',
    established: 2004,
    about: 'Amity Business School Indore is part of the internationally recognised Amity University network. Offering world-class management and professional education, it brings the global Amity brand with its strong corporate connections to the heart of Madhya Pradesh.',
    highlights: ['Part of Amity University (NAAC A+ nationally)', 'International curriculum standards', 'Global alumni network', 'Strong corporate placements'],
    facilities: ['Hostel', 'Library', 'Labs', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 55% marks' },
    ],
    website: 'https://amity.edu/aib/indore',
    logo: '',
  },
  {
    slug: 'avantika-university-ujjain',
    name: 'Avantika University',
    shortName: 'Avantika',
    city: 'Ujjain',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Private University',
    naac: 'A',
    established: 2012,
    about: 'Avantika University in Ujjain is a design-focused multi-disciplinary university known for its unique MBA specialisations in emerging sectors. It offers industry-aligned programmes with strong mentorship from design and business professionals.',
    highlights: ['Unique MBA super-specialisations', 'Design-focused university', 'BFSI & Digital Marketing specialisations', 'Located in Ujjain — the city of Mahakal'],
    facilities: ['Hostel', 'Design Studios', 'Labs', 'Library', 'Sports'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio' },
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: ['Executive MBA', 'Business Analytics', 'BA & AI', 'BFSI', 'Retail Management', 'Digital Marketing', 'Hospitality Management'], eligibility: 'Graduation with 50% marks' },
    ],
    website: 'https://avantikauniversity.edu.in',
    logo: '',
  },
  {
    slug: 'acropolis-aitr-indore',
    name: 'Acropolis Institute of Technology & Research',
    shortName: 'AITR',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'B+',
    established: 2004,
    about: 'Acropolis Institute of Technology & Research is a well-established AICTE-approved autonomous college in Indore. It specialises in engineering, management, and computer applications with strong placement support.',
    highlights: ['AICTE approved autonomous institute', 'Strong B.Tech placements', 'Industry-linked curriculum', 'Experienced faculty'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
    ],
    website: 'https://acropolis.in',
    logo: '',
  },
  {
    slug: 'acropolis-afmr-indore',
    name: 'Acropolis Faculty of Management & Research',
    shortName: 'AFMR',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'B+',
    established: 2006,
    about: 'Acropolis Faculty of Management & Research (AFMR) is the dedicated management school of the Acropolis group, offering quality MBA, BBA, and commerce programmes with strong industry networking and placement support.',
    highlights: ['Dedicated management faculty', 'Strong MBA placement record', 'Industry networking events', 'Part of Acropolis group'],
    facilities: ['Library', 'Classrooms', 'Labs', 'Sports'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
    ],
    website: 'https://acropolis.in',
    logo: '',
  },
  {
    slug: 'christian-eminent-college-indore',
    name: 'Christian Eminent College',
    shortName: 'CEC',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'A',
    established: 1965,
    about: 'Christian Eminent College is one of Indore\'s oldest and most respected colleges, established in 1965. Affiliated to Devi Ahilya Vishwavidyalaya, it is known for its quality education, value-based environment, and long-standing academic tradition.',
    highlights: ['One of Indore\'s oldest colleges (est. 1965)', 'NAAC A Grade accredited', 'Value-based Christian education tradition', 'Trusted by generations of Indore families'],
    facilities: ['Library', 'Labs', 'Sports', 'Chapel', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'M.Com', specializations: [], eligibility: 'B.Com with 50% marks' },
      { level: 'PG', name: 'MA', specializations: [], eligibility: 'BA with 45% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 50% marks' },
    ],
    website: 'https://christianeminentcollege.edu.in',
    logo: '',
  },
  {
    slug: 'indore-institute-of-law',
    name: 'Indore Institute of Law',
    shortName: 'IIL',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Law College',
    naac: 'B+',
    established: 2008,
    about: 'Indore Institute of Law is a dedicated law college offering BCI-approved programmes in legal education. Known for its moot court culture, experienced faculty, and strong bar council connections, it prepares students for careers in law and judiciary.',
    highlights: ['BCI approved law college', 'Active moot court programme', 'Experienced legal faculty', 'Strong judiciary & bar connections'],
    facilities: ['Moot Court', 'Law Library', 'Classrooms', 'Sports'],
    courses: [
      { level: 'UG', name: 'LLB (3 Year)', specializations: [], eligibility: 'Graduation with 45% marks' },
      { level: 'UG', name: 'BA LLB (5 Year)', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA LLB (5 Year)', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB/BA LLB with 55% marks' },
    ],
    website: 'https://iilindore.com',
    logo: '',
  },
  {
    slug: 'iist-indore',
    name: 'Indore Institute of Science & Technology',
    shortName: 'IIST',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'B',
    established: 2001,
    about: 'Indore Institute of Science & Technology is an AICTE-approved autonomous college with over two decades of technical education. It offers engineering, management, and computer science programmes with focus on practical learning.',
    highlights: ['AICTE approved autonomous institute', 'Over 20 years of technical education', 'Industry-ready curriculum', 'Placement support'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
    ],
    website: 'https://indoreinstitute.com',
    logo: '',
  },
  {
    slug: 'chameli-devi-indore',
    name: 'Chameli Devi Institute of Management',
    shortName: 'CDIM',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'B+',
    established: 2002,
    about: 'Chameli Devi Institute of Management is a focused management college offering MBA and BBA programmes with specialisations including Foreign Trade. It is known for its practical approach to business education.',
    highlights: ['Focused management college', 'Foreign Trade specialisation', 'Practical business education', 'Experienced management faculty'],
    facilities: ['Library', 'Labs', 'Classrooms', 'Sports'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: ['General', 'Foreign Trade'], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: ['Marketing', 'Finance', 'HRM', 'Production Management', 'IT', 'Foreign Trade'], eligibility: 'Graduation with 50% marks' },
    ],
    website: 'https://cdgi.edu.in',
    logo: '',
  },
  {
    slug: 'cdgi-indore',
    name: 'Chameli Devi Group of Institutions',
    shortName: 'CDGI',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Group of Colleges',
    naac: 'B+',
    established: 1999,
    about: 'Chameli Devi Group of Institutions is a multi-disciplinary educational group in Indore offering engineering, management, computer applications, and diploma programmes across its campuses.',
    highlights: ['Multi-disciplinary group', 'Engineering & management focus', 'Diploma programmes available', 'Large alumni network'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
      { level: 'Diploma', name: 'Diploma Engineering', specializations: [], eligibility: '10th pass with 35% marks' },
    ],
    website: 'https://cdgi.edu.in',
    logo: '',
  },
  {
    slug: 'malwa-institute-of-technology-indore',
    name: 'Malwa Institute of Technology & Management',
    shortName: 'MITM',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'B',
    established: 2002,
    about: 'Malwa Institute of Technology & Management is an AICTE-approved institution offering engineering and management programmes with practical training and placement support.',
    highlights: ['AICTE approved institute', 'Engineering & management combined', 'Practical training focus', 'Placement assistance'],
    facilities: ['Labs', 'Library', 'Sports', 'Hostel'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: ['HR', 'Marketing', 'Finance', 'Production', 'IT'], eligibility: 'Graduation with 50% marks' },
      { level: 'Diploma', name: 'Diploma Engineering', specializations: [], eligibility: '10th pass with 35% marks' },
    ],
    website: 'https://malwait.com',
    logo: '',
  },
  {
    slug: 'patel-group-indore',
    name: 'Patel Group of Institutes',
    shortName: 'Patel Group',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Group of Institutes',
    naac: 'B',
    established: 2006,
    about: 'Patel Group of Institutes offers a range of technical and management programmes. Known for its affordable education and strong community ties in Indore.',
    highlights: ['Affordable quality education', 'Technical & management courses', 'Community-focused institution', 'Diploma programmes available'],
    facilities: ['Labs', 'Library', 'Sports'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'Diploma', name: 'Diploma Engineering', specializations: [], eligibility: '10th pass with 35% marks' },
    ],
    website: 'https://patelcollege.edu.in',
    logo: '',
  },
  {
    slug: 'svits-indore',
    name: 'Shri Vaishnav Institute of Technology & Science',
    shortName: 'SVITS',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'B+',
    established: 2001,
    about: 'SVITS is an AICTE-approved autonomous engineering and technology institute affiliated to RGPV. It offers B.Tech and postgraduate engineering programmes with a strong technical foundation.',
    highlights: ['AICTE approved autonomous institute', 'RGPV affiliated', 'Strong technical faculty', 'Engineering focus'],
    facilities: ['Labs', 'Library', 'Sports', 'Hostel'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
    ],
    website: 'https://svits.ac.in',
    logo: '',
  },
  {
    slug: 'pips-indore',
    name: 'Pioneer Institute of Professional Studies',
    shortName: 'PIPS',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'B',
    established: 2003,
    about: 'Pioneer Institute of Professional Studies (PIPS) provides professional and vocational education with strong focus on management, commerce, and computer applications. It is known for its career-oriented approach.',
    highlights: ['Career-oriented programmes', 'Management & commerce focus', 'Affordable education', 'Placement assistance'],
    facilities: ['Library', 'Labs', 'Sports'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 50% marks' },
    ],
    website: 'https://pips.ac.in',
    logo: '',
  },
  {
    slug: 'indore-management-institute',
    name: 'Indore Management Institute & Research Centre',
    shortName: 'IMI',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Management College',
    naac: 'B',
    established: 2001,
    about: 'Indore Management Institute & Research Centre (IMI) is a focused management school offering MBA and BBA programmes with emphasis on research and practical business skills.',
    highlights: ['Research-oriented management institute', 'Experienced faculty', 'Industry connect', 'Small class sizes for personalised learning'],
    facilities: ['Library', 'Classrooms', 'Labs'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
    ],
    website: 'https://imi.edu.in',
    logo: '',
  },
  {
    slug: 'dsifd-indore',
    name: 'DSIFD Indore',
    shortName: 'DSIFD',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Design College',
    naac: 'N/A',
    established: 1993,
    about: 'DSIFD (Design School of India for Fashion & Design) is one of Indore\'s premier design colleges, offering professional courses in fashion design, interior design, graphic design, and MBA in Design. Known for its creative faculty and industry-connected curriculum.',
    highlights: ['Premiere design college in MP', 'Fashion, Interior & Graphic Design', 'MBA in Design programme', 'Industry projects & internships'],
    facilities: ['Design Studios', 'Library', 'Labs', 'Exhibition Hall'],
    courses: [
      { level: 'UG', name: 'B.Des', specializations: ['Fashion Design', 'Interior Design', 'Graphic Design'], eligibility: '10+2 with creative aptitude' },
      { level: 'PG', name: 'MBA in Design', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'M.Des', specializations: [], eligibility: 'B.Des/BA with portfolio' },
      { level: 'Diploma', name: 'Diploma in Design', specializations: ['Fashion', 'Interior', 'Graphic'], eligibility: '10+2 with creative aptitude' },
    ],
    website: 'https://dsifd.com',
    logo: '',
  },
  {
    slug: 'graffiti-institute-indore',
    name: 'Graffiti Institute of Fashion Technology',
    shortName: 'Graffiti',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Design College',
    naac: 'N/A',
    established: 2005,
    about: 'Graffiti Institute of Fashion Technology is a creative design institution in Indore offering fashion design and design programmes. It nurtures creative talent through hands-on studio learning and industry exposure.',
    highlights: ['Fashion design focus', 'Studio-based learning', 'Industry exposure & internships', 'Creative faculty'],
    facilities: ['Design Studios', 'Library', 'Workshops'],
    courses: [
      { level: 'UG', name: 'B.Des', specializations: ['Fashion Design'], eligibility: '10+2 with creative aptitude' },
      { level: 'UG', name: 'BA Fashion Design', specializations: [], eligibility: '10+2 with creative aptitude' },
      { level: 'PG', name: 'M.Des', specializations: [], eligibility: 'B.Des/BA with portfolio' },
      { level: 'Diploma', name: 'Diploma in Fashion Design', specializations: [], eligibility: '10+2' },
    ],
    website: 'https://graffitiinstitute.in',
    logo: '',
  },
  {
    slug: 'chirayu-medical-college-indore',
    name: 'Chirayu Medical College & Hospital',
    shortName: 'Chirayu',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Medical College',
    naac: 'B+',
    established: 2008,
    about: 'Chirayu Medical College & Hospital is an NMC-approved medical college with an attached multi-specialty hospital providing extensive clinical exposure. It offers MBBS and BSc Nursing programmes in a full clinical environment.',
    highlights: ['NMC approved MBBS programme', 'Multi-specialty hospital attached', 'Extensive clinical training', 'BSc Nursing programme'],
    facilities: ['Hospital', 'Hostel', 'Labs', 'Library', 'Simulation Centre'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BSc Nursing', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'PG', name: 'MD / MS', specializations: [], eligibility: 'MBBS + NEET-PG' },
      { level: 'Diploma', name: 'GNM', specializations: [], eligibility: '10+2 (PCB) with 40% marks' },
      { level: 'Diploma', name: 'ANM', specializations: [], eligibility: '10+2 with 40% marks' },
    ],
    website: 'https://chirayumedicalcollege.com',
    logo: '',
  },
  {
    slug: 'lnct-medical-indore',
    name: 'LNCT Medical College',
    shortName: 'LNCT Medical',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Medical College',
    naac: 'B',
    established: 2010,
    about: 'LNCT Medical College is part of the LNCT group offering NMC-approved MBBS, pharmacy, and nursing programmes. It benefits from the strong academic infrastructure of the LNCT group.',
    highlights: ['Part of LNCT group', 'NMC approved MBBS', 'Nursing & pharmacy programmes', 'Group hospital for clinical training'],
    facilities: ['Hospital', 'Hostel', 'Labs', 'Library'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BSc Nursing', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'PG', name: 'MD / MS', specializations: [], eligibility: 'MBBS + NEET-PG' },
      { level: 'Diploma', name: 'GNM', specializations: [], eligibility: '10+2 (PCB) with 40% marks' },
    ],
    website: 'https://lnctmedical.com',
    logo: '',
  },
  {
    slug: 'aimr-indore',
    name: 'Apex Institute of Management & Research',
    shortName: 'AIMR',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Management College',
    naac: 'B',
    established: 2007,
    about: 'Apex Institute of Management & Research (AIMR) is a management-focused institution offering MBA and BBA programmes with practical training, management events, and industry interface programmes.',
    highlights: ['Management-focused college', 'Industry interface events', 'Practical training approach', 'Management events & competitions'],
    facilities: ['Library', 'Classrooms', 'Labs'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'Diploma', name: 'Diploma in Management', specializations: [], eligibility: 'Graduation' },
    ],
    website: 'https://aimrindore.com',
    logo: '',
  },
  {
    slug: 'sushila-devi-bansal-indore',
    name: 'Sushila Devi Bansal College of Engineering',
    shortName: 'SDBC',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Engineering College',
    naac: 'B',
    established: 2004,
    about: 'Sushila Devi Bansal College of Engineering is an AICTE-approved engineering college affiliated to RGPV. It offers B.Tech and M.Tech programmes with a focus on technical excellence.',
    highlights: ['AICTE approved', 'RGPV affiliated', 'Technical focus', 'Practical engineering labs'],
    facilities: ['Labs', 'Library', 'Sports', 'Hostel'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil'], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% marks' },
    ],
    website: 'https://sdbc.ac.in',
    logo: '',
  },
  {
    slug: 'sgsits-indore',
    name: 'Shri GS Institute of Technology & Science',
    shortName: 'SGSITS',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'local',
    type: 'Autonomous College',
    naac: 'A',
    established: 1952,
    about: 'SGSITS is one of Indore\'s oldest and most prestigious technical institutions, established in 1952. NAAC A-grade accredited and RGPV-affiliated, it is widely regarded as one of the best engineering colleges in central India.',
    highlights: ['Established in 1952 — Indore\'s oldest technical institute', 'NAAC A Grade accredited', 'Consistently high JEE/LEET admissions', 'Alumni in top Indian & global companies'],
    facilities: ['Hostel', 'Labs', 'Library', 'Sports Complex', 'Cafeteria'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil', 'Chemical', 'Electrical'], eligibility: '10+2 (PCM) with 50% marks + JEE' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 55% + GATE preferred' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 55% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% + entrance' },
    ],
    website: 'https://sgsits.ac.in',
    logo: '',
  },
  // Tier 3 colleges
  {
    slug: 'astral-college-indore',
    name: 'Astral College',
    shortName: 'Astral',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2008,
    about: 'Astral College offers BBA programmes affiliated to Devi Ahilya Vishwavidyalaya, Indore. It provides quality management education at affordable costs.',
    highlights: ['DAVV affiliated', 'Affordable BBA programme', 'Career guidance', 'Placement support'],
    facilities: ['Library', 'Classrooms'],
    courses: [{ level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' }],
    website: '', logo: '',
  },
  {
    slug: 'arihant-college-indore',
    name: 'Arihant College',
    shortName: 'Arihant',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2006,
    about: 'Arihant College is a DAVV-affiliated institution offering BBA and other programmes with focus on commerce and management education.',
    highlights: ['DAVV affiliated', 'Commerce & management focus', 'Affordable fees', 'Career support'],
    facilities: ['Library', 'Classrooms'],
    courses: [{ level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' }],
    website: '', logo: '',
  },
  {
    slug: 'isba-college-indore',
    name: 'ISBA College',
    shortName: 'ISBA',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2005,
    about: 'ISBA College offers BBA programmes including a specialised BBA in Hotel Management, catering to students interested in both business administration and hospitality management.',
    highlights: ['Hotel Management BBA', 'Hospitality-focused curriculum', 'Industry exposure', 'DAVV affiliated'],
    facilities: ['Library', 'Classrooms', 'Kitchens (HM)'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: ['General', 'Hotel Management'], eligibility: '10+2 with 45% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'oxford-college-indore',
    name: 'Oxford College',
    shortName: 'Oxford College',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2007,
    about: 'Oxford College (not affiliated with Oxford UK) is a local DAVV-affiliated institution in Indore offering BBA programmes.',
    highlights: ['DAVV affiliated', 'Affordable management education', 'Career guidance'],
    facilities: ['Library', 'Classrooms'],
    courses: [{ level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' }],
    website: '', logo: '',
  },
  {
    slug: 'vishisht-school-of-management-indore',
    name: 'Vishisht School of Management',
    shortName: 'VSM',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Management College', naac: 'B', established: 2009,
    about: 'Vishisht School of Management offers BBA and MBA programmes with a focus on developing business leaders through quality management education.',
    highlights: ['Dedicated management school', 'BBA & MBA programmes', 'Industry-oriented teaching', 'Placement support'],
    facilities: ['Library', 'Classrooms', 'Labs'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'altius-college-indore',
    name: 'ALTIUS College',
    shortName: 'ALTIUS',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2010,
    about: 'ALTIUS College offers BBA, B.Com, and BSc programmes affiliated to DAVV. It provides quality undergraduate education with a focus on student development.',
    highlights: ['DAVV affiliated', 'Multi-stream programmes', 'Affordable education', 'Student development focus'],
    facilities: ['Library', 'Classrooms'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'modern-college-management-indore',
    name: 'Modern College of Management',
    shortName: 'MCM',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Management College', naac: 'B', established: 2004,
    about: 'Modern College of Management provides management and technology programmes affiliated to DAVV, with focus on quality and affordable management education.',
    highlights: ['Management & tech programmes', 'DAVV affiliated', 'Affordable quality education', 'Career guidance'],
    facilities: ['Library', 'Labs', 'Classrooms'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'radiant-institute-indore',
    name: 'Radiant Institute of Management',
    shortName: 'Radiant',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Management College', naac: 'B', established: 2008,
    about: 'Radiant Institute of Management focuses on BBA education with hands-on management training and career-oriented approach for students.',
    highlights: ['BBA focused institute', 'Career-oriented approach', 'Hands-on training', 'Placement assistance'],
    facilities: ['Library', 'Classrooms'],
    courses: [{ level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' }],
    website: '', logo: '',
  },
  {
    slug: 'bm-college-indore',
    name: 'BM College',
    shortName: 'BM',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2005,
    about: 'BM College is a DAVV-affiliated multi-stream college offering engineering, computer applications, management and commerce programmes.',
    highlights: ['Multi-stream college', 'DAVV affiliated', 'Engineering & management', 'Affordable fees'],
    facilities: ['Labs', 'Library', 'Classrooms'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'new-era-college-mhow',
    name: 'New Era College',
    shortName: 'New Era',
    city: 'Mhow',
    state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2007,
    about: 'New Era College in Mhow (near Indore) offers BBA programmes for students in the Mhow and surrounding areas.',
    highlights: ['Located in Mhow near Indore', 'DAVV affiliated', 'BBA programme', 'Local community focus'],
    facilities: ['Library', 'Classrooms'],
    courses: [{ level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' }],
    website: '', logo: '',
  },
  {
    slug: 'vikrant-institute-indore',
    name: 'Vikrant Institute of Technology & Management',
    shortName: 'VITM',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Engineering College', naac: 'B', established: 2006,
    about: 'Vikrant Institute of Technology & Management offers engineering, management, and computer applications programmes with practical training approach.',
    highlights: ['Engineering & management combined', 'Practical training', 'RGPV affiliated', 'Placement support'],
    facilities: ['Labs', 'Library', 'Sports', 'Hostel'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'jain-dewakar-indore',
    name: 'Jain Dewakar College',
    shortName: 'JDC',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2003,
    about: 'Jain Dewakar College offers undergraduate arts, commerce, and science programmes affiliated to DAVV, providing quality education at affordable costs.',
    highlights: ['Arts, Commerce & Science streams', 'DAVV affiliated', 'Affordable education', 'Community focus'],
    facilities: ['Library', 'Classrooms'],
    courses: [
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'parijat-college-indore',
    name: 'Parijat College',
    shortName: 'Parijat',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2005,
    about: 'Parijat College offers a range of undergraduate and postgraduate programmes in management, sciences, and education affiliated to DAVV.',
    highlights: ['Multi-discipline programmes', 'DAVV affiliated', 'B.Ed teacher training', 'Management programmes'],
    facilities: ['Library', 'Classrooms', 'Labs'],
    courses: [
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'B.Ed', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
      { level: 'Diploma', name: 'PGDM', specializations: [], eligibility: 'Graduation' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'keshav-nandan-indore',
    name: 'Keshav Nandan Girls College',
    shortName: 'KNGC',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Girls College', naac: 'B', established: 1980,
    about: 'Keshav Nandan Girls College is a dedicated girls\' college in Indore offering B.Com, BA, BSc and BCA programmes in a safe and supportive environment.',
    highlights: ['Girls-only college', 'Safe campus environment', 'Multi-stream UG programmes', 'DAVV affiliated'],
    facilities: ['Library', 'Classrooms', 'Labs'],
    courses: [
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'shri-cloth-market-indore',
    name: 'Shri Cloth Market Girls College',
    shortName: 'SCMGC',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Girls College', naac: 'B', established: 1975,
    about: 'Shri Cloth Market Girls College is one of Indore\'s established girls\' colleges offering commerce, arts and science programmes in a dedicated girls-only environment.',
    highlights: ['Girls-only college', 'Established institution', 'Commerce & Arts focus', 'DAVV affiliated'],
    facilities: ['Library', 'Classrooms'],
    courses: [
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 45% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'rd-memorial-indore',
    name: 'RD Memorial College',
    shortName: 'RDM',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Affiliated College', naac: 'B', established: 2006,
    about: 'RD Memorial College is a DAVV-affiliated institution offering B.Com, BA, BCA, and BBA programmes with quality undergraduate education.',
    highlights: ['Multi-stream UG college', 'DAVV affiliated', 'Affordable education', 'Career support'],
    facilities: ['Library', 'Classrooms', 'Labs'],
    courses: [
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 45% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 45% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 45% marks' },
    ],
    website: '', logo: '',
  },
  {
    slug: 'aurobindo-college-pharmacy-indore',
    name: 'Aurobindo College of Pharmacy',
    shortName: 'ACP',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Pharmacy College', naac: 'B+', established: 2001,
    about: 'Aurobindo College of Pharmacy is a PCI-approved institution offering B.Pharm, M.Pharm, D.Pharm and Pharm.D programmes with strong laboratory infrastructure.',
    highlights: ['PCI approved', 'Complete pharmacy programme range', 'Strong lab infrastructure', 'Industry connections'],
    facilities: ['Pharmacy Labs', 'Library', 'Hostel'],
    courses: [
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'UG', name: 'D.Pharm', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'UG', name: 'Pharm.D', specializations: [], eligibility: '10+2 (PCB) with 50% marks' },
      { level: 'PG', name: 'M.Pharm', specializations: [], eligibility: 'B.Pharm with 55% marks' },
    ],
    website: 'https://sau.ac.in',
    logo: '',
  },
  {
    slug: 'acad-indore',
    name: 'Artemisia College of Art & Design',
    shortName: 'ACAD',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Design College', naac: 'N/A', established: 2012,
    about: 'Artemisia College of Art & Design (ACAD) is a creative arts college in Indore offering B.Des, BFA, and diploma programmes with focus on fine arts, design, and creative expression.',
    highlights: ['Fine arts & design focus', 'B.Des & BFA programmes', 'Creative studio environment', 'Portfolio-based admissions'],
    facilities: ['Art Studios', 'Design Labs', 'Library'],
    courses: [
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with creative aptitude/portfolio' },
      { level: 'UG', name: 'BFA', specializations: [], eligibility: '10+2 with creative aptitude' },
      { level: 'Diploma', name: 'Diploma in Design & Art', specializations: [], eligibility: '10+2' },
    ],
    website: 'https://acadindore.com',
    logo: '',
  },
  {
    slug: 'state-ihm-indore',
    name: 'State Institute of Hotel Management',
    shortName: 'State IHM',
    city: 'Indore', state: 'Madhya Pradesh', country: 'India', section: 'local',
    type: 'Hotel Management', naac: 'N/A', established: 1995,
    about: 'State Institute of Hotel Management, Indore is a government-affiliated hospitality institute offering BSc Hotel Management and diploma programmes, training students for careers in hotels, resorts, and food service industries.',
    highlights: ['Government-affiliated institute', 'BSc Hotel Management', 'Industry exposure', 'Practical hospitality training'],
    facilities: ['Training Kitchen', 'Front Office Lab', 'Library', 'Hostel'],
    courses: [
      { level: 'UG', name: 'BSc Hotel Management', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'Diploma', name: 'Diploma in Hotel Management', specializations: [], eligibility: '10+2 with 45% marks' },
    ],
    website: '', logo: '',
  },
]
