import type { University } from './types'

export const nationalUniversities: University[] = [
  {
    slug: 'iim-indore',
    name: 'IIM Indore',
    shortName: 'IIM Indore',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'national',
    type: 'Premier B-School (IIM)',
    naac: 'A++',
    established: 1996,
    about: 'IIM Indore is one of the most prestigious management institutions in India, part of the elite IIM network. Offering the flagship PGP (MBA), Executive MBA, and the unique 5-year Integrated Programme in Management (IPM), it consistently ranks among India\'s top 5 B-schools.',
    highlights: ['Top 5 B-School in India', 'Flagship PGP (MBA) programme', '5-Year IPM (BBA+MBA)', 'World-class faculty & research', 'Global exchange programmes'],
    facilities: ['World-class campus', 'Hostel', 'Sports Complex', 'Research Centre', 'International Exchange'],
    courses: [
      { level: 'PG', name: 'MBA (PGP)', specializations: [], eligibility: 'Graduation with 50% + CAT score' },
      { level: 'PG', name: 'Executive MBA (EPGP)', specializations: [], eligibility: '5 years work experience + GMAT/CAT' },
      { level: 'UG', name: 'IPM — 5-Year BBA+MBA', specializations: [], eligibility: '10+2 with 60% + IPMAT exam' },
      { level: 'Research', name: 'PhD', specializations: [], eligibility: 'PG with 55% + CAT/GMAT/UGC-NET' },
    ],
    website: 'https://www.iimidr.ac.in',
    logo: '',
  },
  {
    slug: 'symbiosis-university',
    name: 'Symbiosis International University',
    shortName: 'SIU',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    section: 'national',
    type: 'Deemed University',
    naac: 'A',
    established: 2002,
    about: 'Symbiosis International University (SIU) is a prestigious deemed university in Pune offering diverse programmes across management, law, technology, health sciences, and liberal arts. It is consistently ranked among India\'s top private universities.',
    highlights: ['NAAC A Grade', 'Multiple autonomous institutes', 'International diversity', 'Strong industry connections', 'NIRF ranked'],
    facilities: ['Hostel', 'Sports Complex', 'Library', 'Research Centres', 'Wi-Fi campus'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% + SET exam' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% + SET' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% + SET' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45% + SET' },
      { level: 'UG', name: 'BBA LLB', specializations: [], eligibility: '10+2 with 45% + SET' },
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 50% + JEE' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% + SET' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 50% + SET' },
      { level: 'PG', name: 'MBA', specializations: ['Finance', 'Marketing', 'HR', 'Operations', 'International Business'], eligibility: 'Graduation with 50% + SNAP exam' },
    ],
    website: 'https://www.siu.edu.in',
    logo: '',
  },
  {
    slug: 'nmims',
    name: 'NMIMS (Narsee Monjee Institute)',
    shortName: 'NMIMS',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    section: 'national',
    type: 'Deemed University',
    naac: 'A',
    established: 1981,
    about: 'NMIMS (Narsee Monjee Institute of Management Studies) is a highly ranked deemed university with its flagship campus in Mumbai and additional campuses across India. Renowned for its MBA, engineering, pharmacy, and design programmes.',
    highlights: ['Top-ranked deemed university', 'Flagship Mumbai campus', 'Multiple pan-India campuses', 'Strong MBA & B.Tech placements', 'NIRF ranked'],
    facilities: ['Hostel', 'Library', 'Labs', 'Sports', 'Innovation Centre'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% + NPAT exam' },
      { level: 'UG', name: 'B.Tech', specializations: [], eligibility: '10+2 (PCM) with 50% + NPAT' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% + NPAT' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio + NPAT' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% + NPAT' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 50% + NPAT' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45%' },
      { level: 'UG', name: 'BBA LLB', specializations: [], eligibility: '10+2 with 50% + NPAT' },
      { level: 'PG', name: 'MBA', specializations: ['Finance', 'Marketing', 'HR', 'Operations', 'Pharmaceutical Management'], eligibility: 'Graduation with 50% + NMAT exam' },
    ],
    website: 'https://www.nmims.edu',
    logo: '',
  },
  {
    slug: 'amity-university',
    name: 'Amity University',
    shortName: 'Amity',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    section: 'national',
    type: 'Private University',
    naac: 'A+',
    established: 2005,
    about: 'Amity University is India\'s largest private university group with 13+ campuses across India and international presence. NAAC A+ accredited, it offers 250+ programmes and is known for its world-class infrastructure and global partnerships.',
    highlights: ['NAAC A+ — India\'s top private university', '13+ campuses pan-India', '250+ programmes', 'Global partnerships & exchange', 'Strong placement record'],
    facilities: ['World-class campus', 'Hostel', 'Sports', 'Research Labs', 'International Centre'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil', 'AI', 'Data Science'], eligibility: '10+2 (PCM) with 55% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45%' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio' },
      { level: 'UG', name: 'B.Arch', specializations: [], eligibility: '10+2 (PCM) with 50% + NATA' },
      { level: 'PG', name: 'MBA', specializations: ['Finance', 'Marketing', 'HR', 'Operations', 'IB', 'IT'], eligibility: 'Graduation with 55% marks' },
    ],
    website: 'https://www.amity.edu',
    logo: '',
  },
  {
    slug: 'lpu',
    name: 'Lovely Professional University',
    shortName: 'LPU',
    city: 'Phagwara',
    state: 'Punjab',
    country: 'India',
    section: 'national',
    type: 'Private University',
    naac: 'A++',
    established: 2005,
    about: 'Lovely Professional University (LPU) is India\'s largest private university by student strength, located in Punjab. NAAC A++ accredited, it offers 700+ programmes across diverse disciplines with outstanding placement records and global exposure.',
    highlights: ['NAAC A++ — highest rated', 'India\'s largest private university', '700+ programmes', 'Record-breaking placements', 'World Skills champion students'],
    facilities: ['Mega campus', 'Hostel', 'Sports Complex', 'Hospital on campus', 'Shopping Mall'],
    courses: [
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil', 'AI/ML', 'Cybersecurity'], eligibility: '10+2 (PCM) with 60% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45%' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50%' },
      { level: 'PG', name: 'MBA', specializations: ['Finance', 'Marketing', 'HR', 'Operations', 'IB', 'Analytics'], eligibility: 'Graduation with 55% marks' },
    ],
    website: 'https://www.lpu.in',
    logo: '',
  },
  {
    slug: 'chandigarh-university',
    name: 'Chandigarh University',
    shortName: 'CU',
    city: 'Chandigarh',
    state: 'Punjab',
    country: 'India',
    section: 'national',
    type: 'Private University',
    naac: 'A+',
    established: 2012,
    about: 'Chandigarh University is a NAAC A+ ranked private university and one of the best universities for engineering and management in North India. Known for record placements, world-class campus, and global partnerships.',
    highlights: ['NAAC A+ accredited', 'Record placements 2024', 'QS World University ranked', 'Global industry partnerships', 'Strong research output'],
    facilities: ['World-class campus', 'Hostel', 'Sports Complex', 'Research Labs', 'Incubation Centre'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil', 'AI/ML', 'DS'], eligibility: '10+2 (PCM) with 60% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45%' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50%' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio' },
      { level: 'PG', name: 'MBA', specializations: ['Finance', 'Marketing', 'HR', 'Operations', 'Analytics'], eligibility: 'Graduation with 55% marks' },
    ],
    website: 'https://www.cuchd.in',
    logo: '',
  },
  {
    slug: 'manipal-university',
    name: 'Manipal University',
    shortName: 'Manipal',
    city: 'Manipal',
    state: 'Karnataka',
    country: 'India',
    section: 'national',
    type: 'Deemed University',
    naac: 'A++',
    established: 1953,
    about: 'Manipal Academy of Higher Education is one of India\'s most reputed deemed universities with campuses across India and internationally. Strong in medical, engineering, management and allied health sciences since 1953.',
    highlights: ['NAAC A++ — Established 1953', 'Medical & Engineering powerhouse', 'International campuses', 'Strong alumni network', 'QS World Ranked'],
    facilities: ['World-class campus', 'Teaching Hospital', 'Hostel', 'Sports', 'Research Labs'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BDS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil', 'IT', 'Chemical'], eligibility: '10+2 (PCM) with 60% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50%' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45%' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 55% marks' },
    ],
    website: 'https://manipal.edu',
    logo: '',
  },
  {
    slug: 'vit-university',
    name: 'VIT University',
    shortName: 'VIT',
    city: 'Vellore',
    state: 'Tamil Nadu',
    country: 'India',
    section: 'national',
    type: 'Deemed University',
    naac: 'A++',
    established: 1984,
    about: 'VIT (Vellore Institute of Technology) is one of India\'s top-ranked deemed universities, consistently ranked in QS World University Rankings. Known for cutting-edge engineering, technology, and management programmes with strong international exposure.',
    highlights: ['NAAC A++ | QS World Ranked', 'Top engineering university', 'VITEEE — competitive entrance', 'Strong tech placements', 'Research & innovation focus'],
    facilities: ['World-class campus', 'Hostel', 'Research Labs', 'Sports Complex', 'Innovation Park'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil', 'AI', 'DS', 'Biotech'], eligibility: '10+2 (PCM) with 60% + VITEEE' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 55% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 55% marks' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 55% + VITMEE/CAT/MAT' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 55% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 60% + GATE preferred' },
    ],
    website: 'https://vit.ac.in',
    logo: '',
  },
  {
    slug: 'srm-university',
    name: 'SRM University',
    shortName: 'SRM',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    section: 'national',
    type: 'Deemed University',
    naac: 'A++',
    established: 1985,
    about: 'SRM Institute of Science and Technology is a NAAC A++ deemed university with multiple campuses. One of South India\'s most sought-after universities, strong in medicine, engineering, management and law programmes.',
    highlights: ['NAAC A++', 'Medical & Engineering excellence', 'Multiple campuses', 'Strong international partnerships', 'High placement rates'],
    facilities: ['Teaching Hospital', 'Hostel', 'Labs', 'Sports', 'Research Centre'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'IT', 'ECE', 'ME', 'Civil', 'Biotech', 'AI'], eligibility: '10+2 (PCM) with 55% + SRMJEEE' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45%' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50%' },
      { level: 'UG', name: 'B.Des', specializations: [], eligibility: '10+2 with portfolio' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 55% marks' },
    ],
    website: 'https://www.srmist.edu.in',
    logo: '',
  },
  {
    slug: 'sharda-university',
    name: 'Sharda University',
    shortName: 'Sharda',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    section: 'national',
    type: 'Private University',
    naac: 'A',
    established: 2009,
    about: 'Sharda University is a leading private university in Greater Noida known for its diverse student body from 80+ countries. It offers programmes in medicine, engineering, law, management and more with strong international diversity.',
    highlights: ['Students from 80+ countries', 'MBBS programme', 'Strong international diversity', 'NAAC A Grade', 'Affordable for quality'],
    facilities: ['Hostel', 'Hospital', 'Labs', 'Sports', 'International Student Centre'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Civil', 'IT'], eligibility: '10+2 (PCM) with 55% marks' },
      { level: 'UG', name: 'BBA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BCA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'B.Com', specializations: [], eligibility: '10+2 (Commerce) with 50% marks' },
      { level: 'UG', name: 'BA', specializations: [], eligibility: '10+2 with 50% marks' },
      { level: 'UG', name: 'BSc', specializations: [], eligibility: '10+2 (Science) with 50% marks' },
      { level: 'UG', name: 'LLB', specializations: [], eligibility: 'Graduation with 45%' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50%' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 50% marks' },
    ],
    website: 'https://www.sharda.ac.in',
    logo: '',
  },
  {
    slug: 'bits-pilani',
    name: 'BITS Pilani',
    shortName: 'BITS',
    city: 'Pilani',
    state: 'Rajasthan',
    country: 'India',
    section: 'national',
    type: 'Deemed University',
    naac: 'A',
    established: 1964,
    about: 'BITS Pilani is one of India\'s most prestigious and competitive institutions for engineering and sciences. Entry is solely through BITSAT. Known for its rigorous academics, practice school internships, and outstanding alumni in global tech companies.',
    highlights: ['One of India\'s top 3 engineering institutes', 'Entry via BITSAT — highly competitive', 'Practice School industry exposure', 'World-renowned alumni (Sabeer Bhatia, etc.)', 'Multiple campuses including Dubai'],
    facilities: ['World-class campus', 'Hostel', 'Research Labs', 'Sports', 'Innovation Centre'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Chemical', 'Civil', 'Manufacturing'], eligibility: '10+2 (PCM) with 75% + BITSAT' },
      { level: 'UG', name: 'MSc', specializations: ['Physics', 'Chemistry', 'Maths', 'Biological Sciences', 'Economics'], eligibility: '10+2 with 75% + BITSAT' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'B.Tech/BSc + CAT/GMAT' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech + GATE' },
      { level: 'Research', name: 'PhD', specializations: [], eligibility: 'PG in relevant field' },
    ],
    website: 'https://www.bits-pilani.ac.in',
    logo: '',
  },
  {
    slug: 'thapar-university',
    name: 'Thapar University',
    shortName: 'Thapar',
    city: 'Patiala',
    state: 'Punjab',
    country: 'India',
    section: 'national',
    type: 'Deemed University',
    naac: 'A',
    established: 1956,
    about: 'Thapar Institute of Engineering and Technology is a renowned deemed university in Patiala, consistently ranked among India\'s top 20 engineering institutions. Strong in engineering, sciences, and management with excellent research output.',
    highlights: ['Consistently top 20 engineering university', 'Strong research culture', 'Industry-linked programmes', 'High graduate employability', 'NAAC A Grade'],
    facilities: ['Campus', 'Hostel', 'Research Labs', 'Sports', 'Library'],
    courses: [
      { level: 'UG', name: 'B.Tech', specializations: ['CSE', 'ECE', 'ME', 'Chemical', 'Civil', 'Biotechnology'], eligibility: '10+2 (PCM) with 60% + JEE Mains' },
      { level: 'PG', name: 'MBA', specializations: [], eligibility: 'Graduation with 55% + CAT/MAT' },
      { level: 'PG', name: 'MCA', specializations: [], eligibility: 'BCA/BSc with 55% marks' },
      { level: 'PG', name: 'M.Tech', specializations: [], eligibility: 'B.Tech with 60% + GATE' },
      { level: 'UG', name: 'BSc', specializations: ['Physics', 'Chemistry', 'Maths'], eligibility: '10+2 (Science) with 60% marks' },
      { level: 'PG', name: 'MSc', specializations: [], eligibility: 'BSc with 55% marks' },
    ],
    website: 'https://www.thapar.edu',
    logo: '',
  },
  {
    slug: 'symbiosis-law-school-pune',
    name: 'Symbiosis Law School, Pune',
    shortName: 'SLS Pune',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    section: 'national',
    type: 'Law School',
    naac: 'A+',
    established: 1977,
    about: 'Symbiosis Law School (SLS) Pune is one of India\'s top law schools, consistently ranked among the best in the country. Part of Symbiosis International University, it offers BCI-approved LLB, BA LLB, BBA LLB, and LLM programmes.',
    highlights: ['India\'s top law school', 'BCI approved programmes', 'Moot court champions', 'Strong judiciary connections', 'International law exposure'],
    facilities: ['Moot Court Hall', 'Law Library', 'Hostel', 'Sports', 'Classrooms'],
    courses: [
      { level: 'UG', name: 'LLB (3 Year)', specializations: [], eligibility: 'Graduation with 45% + SLAT' },
      { level: 'UG', name: 'BA LLB (5 Year)', specializations: [], eligibility: '10+2 with 45% + SLAT' },
      { level: 'UG', name: 'BBA LLB (5 Year)', specializations: [], eligibility: '10+2 with 45% + SLAT' },
      { level: 'PG', name: 'LLM', specializations: ['Business Law', 'IP Law', 'Constitutional Law'], eligibility: 'LLB/BA LLB with 55% marks' },
    ],
    website: 'https://www.symlaw.ac.in',
    logo: '',
  },
  {
    slug: 'nliu-bhopal',
    name: 'NLIU Bhopal',
    shortName: 'NLIU',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    country: 'India',
    section: 'national',
    type: 'National Law University',
    naac: 'A',
    established: 1997,
    about: 'National Law Institute University (NLIU) Bhopal is one of India\'s premier National Law Universities, established by Act of MP State Legislature. Admission through CLAT, it is among the top NLUs and is the NLU of Madhya Pradesh.',
    highlights: ['National Law University — MP', 'Admission via CLAT', 'Top NLU ranking', 'Experienced judiciary faculty', 'Moot court tradition'],
    facilities: ['Hostel', 'Moot Court', 'Law Library', 'Sports', 'Computer Lab'],
    courses: [
      { level: 'UG', name: 'BA LLB (5 Year)', specializations: [], eligibility: '10+2 with 45% + CLAT' },
      { level: 'PG', name: 'LLM', specializations: [], eligibility: 'LLB/BA LLB with 55% + CLAT-PG' },
      { level: 'Research', name: 'PhD', specializations: [], eligibility: 'LLM with 55% + entrance' },
    ],
    website: 'https://nliu.ac.in',
    logo: '',
  },
  {
    slug: 'manipal-medical',
    name: 'Manipal College of Medical Sciences',
    shortName: 'MCMS',
    city: 'Manipal',
    state: 'Karnataka',
    country: 'India',
    section: 'national',
    type: 'Medical College',
    naac: 'A++',
    established: 1990,
    about: 'Manipal College of Medical Sciences is part of the prestigious Manipal Academy. Offering MBBS, BDS, nursing and allied health sciences, it provides world-class medical education with extensive clinical exposure at Kasturba Hospital.',
    highlights: ['Part of Manipal Academy (NAAC A++)', 'Kasturba Hospital clinical training', 'NMC & DCI recognised', 'International medical standards', 'Research opportunities'],
    facilities: ['800-bed Teaching Hospital', 'Hostel', 'Simulation Labs', 'Library', 'Sports'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BDS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BSc Nursing', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'PG', name: 'MD / MS', specializations: [], eligibility: 'MBBS + NEET-PG' },
      { level: 'PG', name: 'MDS', specializations: [], eligibility: 'BDS + NEET-PG' },
    ],
    website: 'https://manipal.edu/mcms.html',
    logo: '',
  },
  {
    slug: 'sri-ramachandra',
    name: 'Sri Ramachandra University',
    shortName: 'SRMC',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    section: 'national',
    type: 'Medical University',
    naac: 'A+',
    established: 1985,
    about: 'Sri Ramachandra Institute of Higher Education and Research (SRIHER) is a premier medical deemed university in Chennai. It offers MBBS, BDS, pharmacy, nursing and allied health programmes with 1600+ bed Sri Ramachandra Hospital.',
    highlights: ['1600-bed teaching hospital', 'NAAC A+ medical university', 'Multiple health sciences programmes', 'Strong clinical training', 'Research-focused'],
    facilities: ['Teaching Hospital', 'Hostel', 'Labs', 'Library', 'Sports'],
    courses: [
      { level: 'UG', name: 'MBBS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BDS', specializations: [], eligibility: '10+2 (PCB) with 50% + NEET' },
      { level: 'UG', name: 'BSc Nursing', specializations: [], eligibility: '10+2 (PCB) with 45% marks' },
      { level: 'UG', name: 'B.Pharm', specializations: [], eligibility: '10+2 (PCB) with 50%' },
      { level: 'PG', name: 'MD / MS', specializations: [], eligibility: 'MBBS + NEET-PG' },
      { level: 'PG', name: 'MDS', specializations: [], eligibility: 'BDS + NEET-PG' },
    ],
    website: 'https://www.sriramachandra.edu.in',
    logo: '',
  },
  {
    slug: 'ihm-india',
    name: 'IHM Aurangabad / IHM Mumbai',
    shortName: 'IHM',
    city: 'Aurangabad / Mumbai',
    state: 'Maharashtra',
    country: 'India',
    section: 'national',
    type: 'Hotel Management',
    naac: 'A',
    established: 1988,
    about: 'Institute of Hotel Management (IHM) Aurangabad and IHM Mumbai are premier hotel management institutes affiliated to NCHMCT and the National Council for Hotel Management. Known for producing hospitality professionals for top hotel chains.',
    highlights: ['NCHMCT affiliated', 'Top hotel management institutes', 'Industry placements in Taj, Marriott, etc.', 'Culinary arts training', 'Strong alumni in hospitality'],
    facilities: ['Training Kitchen', 'Restaurant', 'Housekeeping Lab', 'Front Office Lab', 'Hostel'],
    courses: [
      { level: 'UG', name: 'BSc Hotel Management', specializations: [], eligibility: '10+2 with 50% + NCHMCT JEE' },
      { level: 'Diploma', name: 'Diploma in Hotel Management', specializations: [], eligibility: '10+2 with 45% marks' },
    ],
    website: 'https://ihm-aurangabad.com',
    logo: '',
  },
  {
    slug: 'wgsha-manipal',
    name: 'WGSHA Manipal',
    shortName: 'WGSHA',
    city: 'Manipal',
    state: 'Karnataka',
    country: 'India',
    section: 'national',
    type: 'Hotel Management',
    naac: 'A++',
    established: 1987,
    about: 'Welcomgroup Graduate School of Hotel Administration (WGSHA) at Manipal is one of India\'s most prestigious hotel management schools, established in partnership with ITC Welcomgroup Hotels. Consistently ranked the best HM school in India.',
    highlights: ['India\'s #1 hotel management school', 'ITC Welcomgroup partnership', 'Part of Manipal Academy (NAAC A++)', 'International hospitality curriculum', 'Top hotel placements globally'],
    facilities: ['Training Hotel', 'Culinary Arts Lab', 'Front Office Lab', 'Hostel', 'Sports'],
    courses: [
      { level: 'UG', name: 'BSc Hotel Management', specializations: [], eligibility: '10+2 with 50% + NCHMCT JEE' },
      { level: 'PG', name: 'MBA in Hospitality', specializations: [], eligibility: 'Graduation with 50% marks' },
    ],
    website: 'https://manipal.edu/wgsha.html',
    logo: '',
  },
]
